name: docker-image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      -
        name: Build and push clock
        uses: docker/build-push-action@v6
        with:
          context: ./pomodoro-clock
          push: true
          tags: gabintc/clock:latest
      
      -
        name: Build and push simongame
        uses: docker/build-push-action@v6
        with:
          context: ./Simon-Game
          push: true
          tags: gabintc/simongame:latest
